### ISSUE TITLE
Unable to see item when there is only 1 item in table

### ISSUE THREAD

**Issue by serendipity30** [simplymequeeny/dynamodb-client-web-gui#1]
When there is only one item in any table, the GUI does not show that item in Firefox v54.0.1 (64-bit) (in Windows 10 - 64 bit OS). The item appears but its just not view-able. Chrome and IE shows them properly.

Attached is the screenshot of the same
![image](https://user-images.githubusercontent.com/20826808/27896985-488470dc-61d2-11e7-93c9-cae11e1a2c38.png)

**Comment by simplymequeeny** [comment]
yup noticed that too.  will look at it.  thanks for reminding me this.

**Comment by simplymequeeny** [comment]
Hi, I updated the ui-grid to version 4.0.6.  tested it and its working for me.  can u please check if it is ok now?  if still not working.  can u please give me more details like are connecting to local or aws dynamodb, how many data does has or steps to recreate it.  Thanks

**Comment by serendipity30** [comment]
Issue still persists. You need to give plenty of space so that items can be displayed properly. I can see it a little bit of the record but not completely, it is still partially cut when there is only one item. 

When there are 2 items, it shows only 1 item with scroll bar. 

When there are 18 items, it shows only first 10 items with scroll bar when there is a plenty of space in browser down below, can you increase this to default to at least 20, as this issue is present in all browsers? 

So the 2 main issues are: 
1. When there is only 1 item, it displays item partially when you upgraded grid js to 4.0.6. This issue is only in Firefox.
2. Default text area shows 10 items which needs to be increased to at least 20 so that browser space can be utilized and more items are visible in that text area without need of scroll bar. This issue is present in all browsers.

Note: All of this is tested against local AWS DynamoDB Jar.

**Comment by simplymequeeny** [comment]
i set the grid's width and height instead of using auto which causing the error.   Please update your code and check.  thanks again

**Comment by serendipity30** [comment]
Item #1 is fixed but Item #2 is still open. Can you increase default text area height and make it double so that it can display more records rather than scrollbar?? The space is being wasted.

**Comment by simplymequeeny** [comment]
will work on the item #2

**Comment by serendipity30** [comment]
Any update on item #2? Should I open separate request for this?

**Comment by simplymequeeny** [comment]
Hi I updated the web layout. 

I couldnt adjust the grid to make it 20 rows because it doesnt look good on my laptop screen.

Please change the values of class "data-grid" in the /src/main/resources/static/css/app.css file to suite your need.  the default value is

.data-grid {
    width: 100%;
    height: 500px;
    color: black;
}

Thanks
